### PR TITLE
Improving the Awesome-book project

### PR DESCRIPTION
**Pull request by Chawki-Mbarki**
# Hello 👋

## This pull request contains the following changes:

- Re-factored the HTML structure for better styling. 🛠️
- Added global styles and improved the overall look of the webpage. 🎨
- Styled the books section to match the given design. 📚
- Made small adjustments to improve UX, such as adding placeholder text and input validation. 🙌
- Added the isValid function to verify user inputs and enable/disable - the add button accordingly. 🔒
- Made small adjustments to improve the UI to match the given design, such as adding a decoration line and changing button colors. ✨

### Please review the changes and let me know if you have any feedback or suggestions.

Thank you. 😊

### CODE REVIEW

**Comment by KDlamini** [comment]
## Status: Invalid 🔴 

### Hi @chawkimbarki 🙋‍♀️,  

While you made a great effort in this project, I can't review your code.

## Invalid Code Review Request
 
You have submitted a project that has a README that is not professional. Here is a key point to consider when documenting your README.

- Kindly delete the live demo section if the application is not deployed. If project requirements say to deploy the project, the section should be restored and the link updated. ✖️ 

image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by mukhammadrizooff — APPROVED** [review]
Hi @TEAM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
- No linter errors ✔️ 
- Correct GitHub Flow ✔️ 
- Good implementations ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Chawki-Mbarki** [comment]
Hey @KDlamini  👋
I kept re-reading the project requirements and I didn't see any mention of deleting the live demo section .




Can you explain why you marked this project as invalid and provide a screenshot of the project requirement that we didn't follow.

**Comment by KDlamini** [comment]
Hi @chawkimbarki,

In a way, you will not find it in any of the project requirements for any project. However, it is very much on the guidelines on what comprises a well-documented and professional README. A well-documented and professional README is required for all submissions for any milestone even if it is not mentioned in the project requirements.

I hope that answers your question.

**Pull request merged**
